### ISSUE TITLE
Method on toggling helper for existing toggles

### ISSUE THREAD

**Issue by debugloop** [idanarye/nvim-impairative#2]
Hi, really appreciate the plugin!

I think there's one method missing from the `toggling` helper, which is a sort of method that can trigger existing entry points one to one (the simplest one, probably). Basically [nvim-treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) and [nvim-treesitter-refactor](https://github.com/nvim-treesitter/nvim-treesitter-refactor) come with these for example.

```lua
vim.keymap.set("n", "yot", "<cmd>TSContextToggle<cr>", { desc = "toggle context" })
vim.keymap.set("n", "]ot", "<cmd>TSContextEnable<cr>", { desc = "enable context" })
vim.keymap.set("n", "[ot", "<cmd>TSContextDisable<cr>", { desc = "disable context" })
-- ... same for `TSBufToggle refactor.highlight_definitions` etc
```

should become

```lua
require'impairative'.toggling {
    enable = '[o',
    disable = ']o',
    toggle = 'yo',
}
:toggle(
  key = "t",
  name = "tscontext",
  enable = "<cmd>TSContextEnable<cr>",
  disable = function() vim.cmd("TSContextDisable") end,
  toggle = "<cmd>TSContextToggle<cr>",
)
```

**Comment by idanarye** [comment]
Note though that:

1. Rather than `:toggle`, I prefer to name it `:manual` (since `toggling` is the name of the helper object, and this new method is not the _main_ way to use it. "manual" better conveys the meaning)
2. It won't use the `<cmd>Command<cr>` syntax - just `Command` (because this is what `:command_pair` does)

Other than that - good suggestion!

**Comment by debugloop** [comment]
Awesome, thanks 👍🏻
